name: CI

on: [push, pull_request]

jobs:
  run:
    name: Analyze Project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v4
      
      - name: Install Python
        uses: actions/setup-python@v5.6.0
        with:
          python-version: '3.13'
          cache: 'pip'
      
      - name: Install Packages 
        run: pip install . .[dev]

      - name: Check Code Formatting
        run: ruff format --check src

      - name: Lint Code
        run: ruff check src
