name: Build

on: [push, pull_request]

jobs:
  test:
    name: Unit Tests
    runs-on: ubuntu-latest
    needs: ci
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v5.6.0
        with:
          python-version: '3.13'
          cache: 'pip'

      - name: Install Packages 
        run: pip install .[test]

      - name: Run Tests
        run: python -m src.tests
