name: Unit Testing

on: [push, pull_request]

jobs:
  run:
    name: Run Python Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v5.6.0
        with:
          python-version: '3.13'
          cache: 'pip'

      - name: Install Dependencies
        run: pip install .

      - name: Run Unit Tests
        run: python -m src.tests
